[tool.poetry]
name = "colour-picker-skill"
version = "0.1.0"
description = ""
authors = ["David Buckley <buckley.w.david@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.6"
ask-sdk-core = "^0.1.1"

[tool.poetry.dev-dependencies]
pytest = "^3.0"
